// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-vehicles.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_vehicles_default = defineTool({
  name: "list_vehicles",
  title: "Listar veh\xEDculos",
  description: "Lista veh\xEDculos del taller del usuario autenticado. Permite filtrar por estado y buscar por matr\xEDcula/marca/modelo.",
  inputSchema: {
    status: z.enum(["recibido", "en_reparacion", "pendiente_piezas", "terminado", "entregado", "facturado"]).optional().describe("Filtra por estado del veh\xEDculo."),
    search: z.string().trim().min(1).max(50).optional().describe("B\xFAsqueda por matr\xEDcula, marca o modelo."),
    include_archived: z.boolean().optional().describe("Incluir veh\xEDculos archivados. Por defecto false."),
    limit: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de resultados (por defecto 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, include_archived, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("vehicles").select("id, plate, brand, model, year, status, priority, assigned_to, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (!include_archived) q = q.eq("archived", false);
    if (status) q = q.eq("status", status);
    if (search) {
      const s = search.replace(/[%,]/g, "");
      q = q.or(`plate.ilike.%${s}%,brand.ilike.%${s}%,model.ilike.%${s}%`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { vehicles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-vehicle.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_vehicle_default = defineTool2({
  name: "get_vehicle",
  title: "Obtener veh\xEDculo",
  description: "Devuelve el detalle completo de un veh\xEDculo por su id o por su matr\xEDcula.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("ID del veh\xEDculo."),
    plate: z2.string().trim().min(1).max(20).optional().describe("Matr\xEDcula del veh\xEDculo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, plate }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    if (!id && !plate) {
      return { content: [{ type: "text", text: "Debe indicar id o plate" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let q = supabase.from("vehicles").select("*").limit(1);
    if (id) q = q.eq("id", id);
    else q = q.eq("plate", plate.toUpperCase().replace(/\s+/g, ""));
    const { data, error } = await q.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Veh\xEDculo no encontrado" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { vehicle: data }
    };
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_appointments_default = defineTool3({
  name: "list_appointments",
  title: "Listar citas",
  description: "Lista citas del taller en un rango de fechas (por defecto pr\xF3ximos 7 d\xEDas).",
  inputSchema: {
    from: z3.string().datetime().optional().describe("Fecha inicial ISO 8601."),
    to: z3.string().datetime().optional().describe("Fecha final ISO 8601."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const start = from ?? (/* @__PURE__ */ new Date()).toISOString();
    const end = to ?? new Date(Date.now() + 7 * 24 * 3600 * 1e3).toISOString();
    const { data, error } = await supabase.from("appointments").select("*").gte("appointment_date", start).lte("appointment_date", end).order("appointment_date", { ascending: true }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vzinqlkktnzgciigtycx";
var mcp_default = defineMcp({
  name: "tu-taller-mcp",
  title: "Tu Taller MCP",
  version: "0.1.0",
  instructions: "Herramientas del taller Tu Taller. Consulta veh\xEDculos (\xF3rdenes de trabajo), su estado y las citas del taller del usuario autenticado. Los datos est\xE1n limitados por la organizaci\xF3n del usuario mediante RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_vehicles_default, get_vehicle_default, list_appointments_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
